image: node:latest

stages:
  # - build
  - test
  # - deploy
  

# build-code-job:
#   stage: build
#   script:
#     - npm i
#     - CI=false npm run-script build

# CHANGE development to main later, discuss using 2 EB Instances for a test api
python_unit_tests:
  image: python:3.6-stretch
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - cd backend
    - python tests.py


deploy_development:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "development"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout development
  script:
    - cd backend
    - /root/.local/bin/eb deploy affordaustin-api