image: node:latest

stages:
  - test
  - jstest
  - acceptance
  - deploy

python_unit_tests:
  image: python:3.6-stretch
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - cd backend
    - python3 tests.py

test_jest:
  image:
    name: mcgenius/pp_mocha
    entrypoint: [""]
  stage: jstest
  script:
    - npm i
    - npm test

acceptance_testing:
  stage: acceptance
  script:
   - pip install pipenv
   - pipenv run python src/Tests/acceptance.py

deploy_development:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "development"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout development
  script:
    - cd backend
    - /root/.local/bin/eb deploy affordaustin-api
